name: "Greet User"
description: "Greets a user and returns the current time"
inputs:
  name:
    description: "Name to greet"
    required: true
    default: "World"
outputs:
  time:
    description: "Time of greeting"
runs:
  using: "node20"
  main: "index.js"
